import { NextResponse } from "next/server";
import backtest from "@/data/backtest.json";

export const dynamic = "force-dynamic";

/** GET /api/strategy-lab — the public walk-forward evidence (T26): serves
 *  src/data/backtest.json (regenerated by scripts/backtest-signals.ts) with
 *  a computed per-window cumulative equity curve for both the strategy and
 *  the equal-weight benchmark. No auth: the whole point is that claims are
 *  auditable. The payload is tiny (~15KB) and cached by the CDN-less
 *  dynamic route naturally. */

type WindowRow = { date: string; picks: string[]; netPct: number; benchPct: number };

export async function GET() {
  const windows = (backtest.windows ?? []) as WindowRow[];
  // cumulative equity curve (% gain vs start), compounded per window
  let eq = 100;
  let bench = 100;
  let peak = 100;
  let maxDD = 0;
  const curve = windows.map((w) => {
    eq *= 1 + w.netPct / 100;
    bench *= 1 + w.benchPct / 100;
    peak = Math.max(peak, eq);
    maxDD = Math.min(maxDD, (eq / peak - 1) * 100);
    return {
      date: w.date,
      strategy: +(eq - 100).toFixed(2),
      benchmark: +(bench - 100).toFixed(2),
    };
  });
  return NextResponse.json({
    ...backtest,
    curve,
    curveMaxDD: +maxDD.toFixed(2),
  });
}
