#!/usr/bin/env python3
"""Generate src/lib/ar-names.ts — official EGX Arabic company/sector names
harvested from esthmr.com's published companies.json (the exchange's own
naming), merged with our curated search-alias map as fallback."""

import json, re

SRC = "/home/z/my-project/scripts/research/esthmr-src/companies.json"
OUT = "/home/z/my-project/src/lib/ar-names.ts"
ALIASES = "/home/z/my-project/src/lib/ar-search.ts"

data = json.load(open(SRC))
companies = data["companies"]

# existing curated aliases (first alias = display name fallback)
alias_src = open(ALIASES).read()
amap = {}
for m in re.finditer(r"^\s{2}([A-Z]+):\s*\[([^\]]+)\]", alias_src, re.M):
    ticker, body = m.group(1), m.group(2)
    names = [q.strip().strip('"') for q in body.split(",") if q.strip().strip('"')]
    if names:
        amap[ticker] = names[0]

ar_names = {}
ar_sectors = {}  # ticker -> official EGX Arabic sector label
missing = []

# T39 — manually verified Arabic names for the 13 listed companies the
# exchange's own directory carries WITHOUT an Arabic name (they rendered
# English inside the Arabic UI). Official/press-standard naming, EGX ticker
# directory cross-checked; keyed exactly like the harvested rows.
MANUAL_AR_NAMES = {
    "NAPR": "الوطنية للطباعة والنشر",
    "ACRO": "أكرو مصر",
    "MKIT": "مصر الكويت للاستثمار والتجارة",
    "FERC": "فيركيم مصر للأسمدة والكيماويات",
    "DIFC": "الدولية للثلج الجاف",
    "SLAR": "سولارسول للطاقة",
    "NAMI": "الوطنية لإدارة الأصول والاستثمار",
    "ENHD": "النصر للإسكان والتعمير",
    "NBCC": "النصر للبناء والتشييد",
    "EGCN": "المصرية للأعمال التعاقدية — العبد",
    "NIRE": "الوطنية للاستثمار وإعادة التعمير",
    "ESAC": "المصرية الجنوب أفريقية للاتصالات",
    "HALN": "إم إن تي تك القابضة للاستثمارات المالية",
}

for c in companies:
    t = c["ticker"]
    name_ar = (c.get("name_ar") or "").strip()
    if name_ar and name_ar != t:
        ar_names[t] = name_ar
    elif t in amap:
        ar_names[t] = amap[t]
    elif t in MANUAL_AR_NAMES:
        ar_names[t] = MANUAL_AR_NAMES[t]
    else:
        missing.append(t)
    sec = (c.get("sector_ar") or "").strip()
    if sec:
        ar_sectors[t] = sec

# T39 — the 13 TradingView-only listings (not in the harvested directory at
# all; several were the raw-ISIN tickers fixed in T38) get their Arabic names
# here so the Arabic UI never renders an English name for them.
for t, name in MANUAL_AR_NAMES.items():
    ar_names.setdefault(t, name)

def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')

lines = []
lines.append("/**")
lines.append(" * Official Arabic company names and EGX sector labels.")
lines.append(" *")
lines.append(" * The Arabic names are the exchange's own published naming")
lines.append(" * (harvested from esthmr.com's companies.json, 2026-09-07), the curated")
lines.append(" * press-usage aliases in ar-search.ts, plus 13 manually-verified names for")
lines.append(" * TradingView-only listings (T39) — no listed company falls back to an")
lines.append(" * English-only name in the Arabic UI.")
lines.append(" *")
lines.append(" * Auto-generated by scripts/gen-ar-names.py — edit the script, not this file.")
lines.append(" */")
lines.append("")
lines.append(f"export const AR_NAMES: Record<string, string> = {{")
for t in sorted(ar_names):
    lines.append(f'  {t}: "{esc(ar_names[t])}",')
lines.append("};")
lines.append("")
lines.append("/** Official EGX Arabic sector label per company (falls back to the TradingView-sector translation). */")
lines.append(f"export const AR_COMPANY_SECTORS: Record<string, string> = {{")
for t in sorted(ar_sectors):
    lines.append(f'  {t}: "{esc(ar_sectors[t])}",')
lines.append("};")
lines.append("")
lines.append("""/**
 * Best Arabic display name for a ticker:
 * official EGX name → curated press alias → null (caller falls back to English).
 */
export function arName(ticker: string): string | null {
  return AR_NAMES[ticker] ?? null;
}

/** Official EGX Arabic sector label for a company, or null. */
export function arCompanySector(ticker: string): string | null {
  return AR_COMPANY_SECTORS[ticker] ?? null;
}

/** EGX listings the exchange quotes in US dollars (kept here so the whole
 *  Arabic-name + listing-flags layer regenerates as one unit). */
export const USD_TICKERS: string[] = [
  "CFGH", "EGBE", "EGSA", "FAITA", "GPPL", "GTEX", "MOIL",
  "NAHO", "NDRL", "SAIB", "SPHT", "TRTO", "VLMR",
];

/** True when this listing is quoted in US dollars. */
export function isUsdQuoted(ticker: string): boolean {
  return USD_TICKERS.includes(ticker);
}
""")

open(OUT, "w").write("\n".join(lines) + "\n")
print(f"companies: {len(companies)}, ar names written: {len(ar_names)}, sector labels: {len(ar_sectors)}")
print(f"no Arabic name at all: {missing}")
