#!/usr/bin/env python3
"""Generate src/lib/ar-names.ts — official EGX Arabic company/sector names
harvested from esthmr.com's published companies.json (the exchange's own
naming), merged with our curated search-alias map as fallback."""

import json, re

SRC = "/home/z/my-project/scripts/research/esthmr-src/companies.json"
OUT = "/home/z/my-project/src/lib/ar-names.ts"
ALIASES = "/home/z/my-project/src/lib/ar-search.ts"

data = json.load(open(SRC))
companies = data["companies"]

# existing curated aliases (first alias = display name fallback)
alias_src = open(ALIASES).read()
amap = {}
for m in re.finditer(r"^\s{2}([A-Z]+):\s*\[([^\]]+)\]", alias_src, re.M):
    ticker, body = m.group(1), m.group(2)
    names = [q.strip().strip('"') for q in body.split(",") if q.strip().strip('"')]
    if names:
        amap[ticker] = names[0]

ar_names = {}
ar_sectors = {}  # ticker -> official EGX Arabic sector label
missing = []
for c in companies:
    t = c["ticker"]
    name_ar = (c.get("name_ar") or "").strip()
    if name_ar and name_ar != t:
        ar_names[t] = name_ar
    elif t in amap:
        ar_names[t] = amap[t]
    else:
        missing.append(t)
    sec = (c.get("sector_ar") or "").strip()
    if sec:
        ar_sectors[t] = sec

def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')

lines = []
lines.append("/**")
lines.append(" * Official Arabic company names and EGX sector labels.")
lines.append(" *")
lines.append(" * The Arabic names are the exchange's own published naming")
lines.append(" * (harvested from esthmr.com's companies.json, 2026-09-07) —")
lines.append(" * 270 of 284 listed companies carry one; the remainder fall back to")
lines.append(" * the curated press-usage aliases in ar-search.ts, then to the")
lines.append(" * English name.")
lines.append(" *")
lines.append(" * Auto-generated by scripts/gen-ar-names.py — edit the script, not this file.")
lines.append(" */")
lines.append("")
lines.append(f"export const AR_NAMES: Record<string, string> = {{")
for t in sorted(ar_names):
    lines.append(f'  {t}: "{esc(ar_names[t])}",')
lines.append("};")
lines.append("")
lines.append("/** Official EGX Arabic sector label per company (falls back to the TradingView-sector translation). */")
lines.append(f"export const AR_COMPANY_SECTORS: Record<string, string> = {{")
for t in sorted(ar_sectors):
    lines.append(f'  {t}: "{esc(ar_sectors[t])}",')
lines.append("};")
lines.append("")
lines.append("""/**
 * Best Arabic display name for a ticker:
 * official EGX name → curated press alias → null (caller falls back to English).
 */
export function arName(ticker: string): string | null {
  return AR_NAMES[ticker] ?? null;
}

/** Official EGX Arabic sector label for a company, or null. */
export function arCompanySector(ticker: string): string | null {
  return AR_COMPANY_SECTORS[ticker] ?? null;
}
""")

open(OUT, "w").write("\n".join(lines) + "\n")
print(f"companies: {len(companies)}, ar names written: {len(ar_names)}, sector labels: {len(ar_sectors)}")
print(f"no Arabic name at all: {missing}")
