import { NextResponse } from "next/server";
import { fetchUniverse, companyRow } from "@/lib/market";
import rawInsiders from "@/data/insiders.json";
import rawOwnership from "@/data/ownership-lens.json";

/** GET /api/ownership-lens — the عدسة الملكية (Ownership Lens) payload.
 *
 *  Merges three REAL layers:
 *   1. the LIVE universe (every listed stock with its sector, market cap and
 *      today's change) — the map canvas;
 *   2. the investor registry + documented edges from the official EGX
 *      disclosure archive (src/data/ownership-lens.json, generated by
 *      scripts/t57-build-ownership.mjs) — the lens;
 *   3. per-company insider-filing activity counts (90-day window) so the map
 *      can pulse the companies with live disclosure traffic.
 *
 *  Nothing is simulated: edges carry dates, share counts and links to the
 *  official filing pages; ownership percentages are deliberately NOT shown
 *  because the exchange's live top-10 tables are not part of our sources. */

export const dynamic = "force-dynamic";

type LensEdge = {
  investorId: string;
  ticker: string;
  self: boolean;
  boughtShares: number;
  soldShares: number;
  filings: number;
  firstDate: string;
  lastDate: string;
  links: string[];
};

type LensInvestor = {
  id: string;
  ticker: string | null;
  group: boolean;
  nameEn: string;
  nameAr: string;
  crossHoldings: number;
  filings: number;
};

const ownership = rawOwnership as unknown as {
  asOf: string;
  generatedAt: string;
  source: string;
  sourceAr: string;
  basis: string;
  basisAr: string;
  noteEn: string;
  noteAr: string;
  investors: LensInvestor[];
  edges: LensEdge[];
};

const insiders = rawInsiders as unknown as { asOf: string; items: { date: string; ticker: string }[] };

// 90-day disclosure-activity window for the map pulses
function within90d(date: string, now: number): boolean {
  const t = Date.parse(`${date}T00:00:00Z`);
  return Number.isFinite(t) && now - t <= 90 * 86_400_000;
}

export async function GET() {
  try {
    const stocks = await fetchUniverse();
    const now = Date.now();

    // live map companies
    const companies = stocks.map((s) => {
      const r = companyRow(s);
      return {
        ticker: r.ticker,
        name: r.name,
        nameAr: r.nameAr,
        sectorEn: r.sectorEn,
        sectorAr: r.sectorGroupAr ?? r.sectorAr,
        sectorCode: r.sectorCode,
        close: r.close,
        changePct: Math.round((s.changePct + Number.EPSILON) * 100) / 100,
        marketCap: s.marketCap,
      };
    });
    const listedSet = new Set(companies.map((c) => c.ticker));

    // filing-activity pulse per company (90d)
    const activity = new Map<string, number>();
    for (const it of insiders.items) {
      if (!within90d(it.date, now)) continue;
      activity.set(it.ticker, (activity.get(it.ticker) ?? 0) + 1);
    }

    // edges restricted to currently-listed targets
    const edges = ownership.edges
      .filter((e) => listedSet.has(e.ticker))
      .map((e) => ({
        investorId: e.investorId,
        ticker: e.ticker,
        self: e.self,
        boughtShares: e.boughtShares,
        soldShares: e.soldShares,
        filings: e.filings,
        firstDate: e.firstDate,
        lastDate: e.lastDate,
        links: e.links,
      }));

    // investor registry with listed-ticker labels resolved
    const investors = ownership.investors.map((inv) => ({
      ...inv,
      crossHoldings: edges.filter((e) => e.investorId === inv.id && !e.self).length,
      listed: inv.ticker ? listedSet.has(inv.ticker) : false,
    }));

    return NextResponse.json(
      {
        ok: true,
        asOf: ownership.asOf,
        generatedAt: ownership.generatedAt,
        source: ownership.source,
        sourceAr: ownership.sourceAr,
        noteEn: ownership.noteEn,
        noteAr: ownership.noteAr,
        total: companies.length,
        companies,
        investors,
        edges,
        activity: Object.fromEntries(activity),
      },
      { headers: { "Cache-Control": "no-store" } }
    );
  } catch (err) {
    return NextResponse.json(
      { ok: false, error: "ownership lens unavailable", detail: err instanceof Error ? err.message : "unknown" },
      { status: 503, headers: { "Cache-Control": "no-store" } }
    );
  }
}
