# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
from reportlab.lib import colors

# XL tier: backgrounds (area > 50%, S ≤ 0.08)
PAGE_BG       = colors.HexColor('#eff0f1')
SECTION_BG    = colors.HexColor('#f0f0f1')

# L tier: surfaces (area 20-50%, S ≤ 0.15)
CARD_BG       = colors.HexColor('#e6e8e9')
TABLE_STRIPE  = colors.HexColor('#edf0f1')

# M tier: structural fills (area 5-20%, S ≤ 0.30)
HEADER_FILL   = colors.HexColor('#3c5967')
COVER_BLOCK   = colors.HexColor('#415762')

# S tier: edges & icons (area 1-5%, S ≤ 0.50)
BORDER        = colors.HexColor('#c3d0d6')
ICON          = colors.HexColor('#4b839f')

# XS tier: emphasis (area < 1%, S ≤ 0.75)
ACCENT        = colors.HexColor('#267eaa')
ACCENT_2      = colors.HexColor('#c84359')

# Typography
TEXT_PRIMARY   = colors.HexColor('#191b1c')
TEXT_MUTED     = colors.HexColor('#7d8387')

# Semantic (low-saturation, area-appropriate)
SEM_SUCCESS   = colors.HexColor('#3f7451')
SEM_WARNING   = colors.HexColor('#a38241')
SEM_ERROR     = colors.HexColor('#af5249')
SEM_INFO      = colors.HexColor('#507daa')
